#include <iostream>

using namespace std;

void Xtest (int test) {
  cout << "В функции Xtest(), значение test равно: " << test <<"\n";
  if (test) throw test;
}

int main() {
  cout << "Начало\n";
  try { // начало try-блока
  cout << "В try-блоке\n";
  Xtest(0);
  Xtest(1);
  Xtest(2);
}
catch (int i) { //перехват ошибки
  cout << "Перехват искючения. Его значение равно: ";
  cout << i << "\n";
}
  cout << "Конец";
return 0;
}

////////////////////////////////////////////////////////////////////////////////////////
#include <iostream>

using namespace std;

void Xhandler (int test) {
  try {
    if(test) throw test;
  }
  catch (int i) {
    cout << "Перехват! Исключение №: " << i << '\n';
  }
}

int main() {
  cout << "Начало\n";
  Xhandler(1);
  Xhandler(2);
  Xhandler(0);
  Xhandler(3);
  cout << "Конец";
return 0;
}
